# Generated by Django 4.2.5 on 2023-11-20 21:08

from django.db import migrations
import user_auth.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_auth.managers.UserManager()),
            ],
        ),
    ]
