from django.db import models
from rest_framework import status

from lectures.models import Lecture
from common.error_definitions import CustomAPIError


def video_file_path(instance, filename):
    '''
    Generate path that has course slug.
    Called when a video file is uploaded to Video model instance.

    Attributes
    ----------------
    instance : Video model instance
    filename : str

    Raises
    ----------------
    400 error
        If uploading for a course that does not exist

    Returns
    ----------------
    String with file path containing course slug
    '''
    course = instance.lecture.course
    if course is None:
        raise CustomAPIError(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail='Associated course not found'
        )
    dir_name = ''.join(filter(str.isalnum, course.slug))
    return '{dirname}/{filename}'.format(
        dirname=dir_name,
        filename=filename
    )


class VideoContent(models.Model):
    '''
    Video model for lectures

    Attributes
    ---------------
    lecture : Reference to Lecture Id
    video_file : File
    created_at: Datetime
        Autogenerated when model is created
    updated_at: Datetime
        Autoupdated when model is updated
    '''

    lecture = models.ForeignKey(
        Lecture,
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )
    video_file = models.FileField(upload_to=video_file_path, max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
