# Generated by Django 4.2.5 on 2023-11-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_is_archived_alter_course_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
