from django.db import models

from .managers import CourseStudentRegistrationManager


class CourseStudentRegistration(models.Model):
    '''
    Registration of a student in a course

    Attributes
    --------------
    user : Reference to User Id
    course : Reference to Course Id
    registered_at : DateTime
        Autogenerated when user registers
    '''
    user = models.ForeignKey(
        'user_auth.User',
        null=True,
        on_delete=models.SET_NULL
    )
    course = models.ForeignKey(
        'courses.Course',
        null=True,
        on_delete=models.SET_NULL
    )
    registered_at = models.DateTimeField(auto_now_add=True)

    objects = CourseStudentRegistrationManager()
