# Generated by Django 4.2.5 on 2024-02-19 22:46

from django.db import migrations, models
import django.db.models.deletion
import video_contents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0004_alter_lecture_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(max_length=300, upload_to=video_contents.models.video_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lectures.lecture')),
            ],
        ),
    ]
