# Generated by Django 4.2.5 on 2024-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_alter_lecture_options'),
        ('video_contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='lecture',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='lecture',
            field=models.ManyToManyField(related_name='videos', to='lectures.lecture'),
        ),
    ]
