# Generated by Django 4.2.5 on 2024-03-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_alter_lecture_options'),
        ('video_contents', '0002_remove_videocontent_lecture_videocontent_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='lecture',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='lectures',
            field=models.ManyToManyField(blank=True, related_name='videos', to='lectures.lecture'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
