# Generated by Django 4.2.5 on 2024-03-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_alter_lecture_options'),
        ('courses', '0002_initial'),
        ('video_contents', '0003_remove_videocontent_lecture_videocontent_lectures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='lectures',
            field=models.ManyToManyField(related_name='videos', to='lectures.lecture'),
        ),
    ]
