# Generated by Django 4.2.5 on 2024-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_contents', '0004_videocontent_course_alter_videocontent_lectures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='lectures',
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='name',
            field=models.CharField(default='Video name', max_length=300, unique=True),
        ),
    ]
