# Generated by Django 4.2.5 on 2024-01-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='seq_no',
        ),
    ]
