# Generated by Django 4.2.5 on 2024-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_remove_lecture_seq_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='seq_no',
            field=models.IntegerField(default=0),
        ),
    ]
