# Generated by Django 4.2.5 on 2024-02-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_lecture_seq_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['seq_no']},
        ),
    ]
